### PR TITLE
Triple speed of random string generation

### PR DESCRIPTION
**Pull request by prokopschield**
Using a Buffer instead of an array of strings is, according to my tests, about 3x as fast.

Test: 10000 random strings of length 3200
Duration using old code: 1754 ms
Duration using new code: 610 ms

Test: 100000 random strings of length 32
Duration using old code: 191 ms
Duration using new code: 123 ms

### CODE REVIEW

**Comment by TheOtterlord** [comment]
@HoloPanio while we're at it, is this used anywhere where a more secure random method would make more sense?

**Comment by HoloPanio** [comment]
> @HoloPanio while we're at it, is this used anywhere where a more secure random method would make more sense?

This will likely be used to generate tokens, rg passwords, keys, etc.

**Comment by TheOtterlord** [comment]
Then we should also switch to using crypto module functions to generate random data in place of `Math.random()`

**Comment by HoloPanio** [comment]
Why use crypto modules?

**Comment by TheOtterlord** [comment]
> Note: Math.random() does not provide cryptographically secure random numbers. Do not use them for anything related to security. Use the Web Crypto API instead, and more precisely the [window.crypto.getRandomValues()](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) method. ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random))

Math.random is not the best way to get random numbers if using that data for security,

**Comment by prokopschield** [comment]
I've implemented the usage of crypto.randomBytes(), with buffering to prevent excessive syscalls.

The resulting code is 82% faster, compared to the previous Math.random() implementation.

**Comment by HoloPanio** [comment]
> I've implemented the usage of crypto.randomBytes(), with buffering to prevent excessive syscalls.
> 
> 
> 
> The resulting code is 82% faster, compared to the previous Math.random() implementation.

What are the numbers?

**Comment by prokopschield** [comment]
```bash
git clone https://github.com/prokopschield/duxcore-randStr-speed
cd duxcore-randStr-speed
make
```

**Comment by prokopschield** [comment]
Results from my laptop:
```
100000 iterations, length=32
Version 1: 130.10504699498415 ms
Version 2: 87.45854400098324 ms
Version 3: 68.09464299678802 ms

10000 iterations, length=6400
Version 1: 2305.3926689997315 ms
Version 2: 894.4706609994173 ms
Version 3: 186.44545199722052 ms

1000 iterations, length=100000
Version 1: 5730.223610006273 ms
Version 2: 1312.9026870056987 ms
Version 3: 210.4658930003643 ms
```

**Comment by HoloPanio** [comment]
Please include the duration to generate a single string of various lengths. 2-8192 chars please.

**Review by overlisted — COMMENTED** [review]
I am not involved in this part of the project

**Comment by prokopschield** [comment]
> Please include the duration to generate a single string of various lengths. 2-8192 chars please.

```
length=2
Version 1: 0.000251004999876022 ms
Version 2: 0.000784776200354099 ms
Version 3: 0.002067044000327587 ms

length=4
Version 1: 0.000312279699742794 ms
Version 2: 0.000692563000321388 ms
Version 3: 0.000652675099670887 ms

length=8
Version 1: 0.000719935700297356 ms
Version 2: 0.000577392999827862 ms
Version 3: 0.000814438800513744 ms

length=16
Version 1: 0.000928484199941158 ms
Version 2: 0.001202490100264549 ms
Version 3: 0.000903014700114727 ms

length=32
Version 1: 0.002049191600084305 ms
Version 2: 0.000994135700166226 ms
Version 3: 0.001764649300277233 ms

length=64
Version 1: 0.003726004900038246 ms
Version 2: 0.001836892899870873 ms
Version 3: 0.000820579400658608 ms

length=128
Version 1: 0.007523952600359917 ms
Version 2: 0.006698166500031948 ms
Version 3: 0.002481174799799919 ms

length=256
Version 1: 0.020823435299098490 ms
Version 2: 0.007877669799327850 ms
Version 3: 0.002152322600781918 ms

length=512
Version 1: 0.033275681599974634 ms
Version 2: 0.013018814100325108 ms
Version 3: 0.002636477799713612 ms

length=1024
Version 1: 0.067173850400745870 ms
Version 2: 0.031516191399097440 ms
Version 3: 0.006147321800887584 ms

length=2048
Version 1: 0.121577964699268330 ms
Version 2: 0.062449826800823210 ms
Version 3: 0.011638350400328637 ms

length=4096
Version 1: 0.221293421600759020 ms
Version 2: 0.077285757800936700 ms
Version 3: 0.020127769599854947 ms

length=8192
Version 1: 0.429856779600679860 ms
Version 2: 0.163743882000446320 ms
Version 3: 0.030723538801074028 ms
```

**Pull request merged**
