### PR TITLE
Hcaptcha register

### PR DESCRIPTION
**Pull request by ajmnz**

### CODE REVIEW

**Review by HoloPanio — APPROVED** [review]
It looks good to me.

**Comment by ajmnz** [comment]
Waiting for https://github.com/hCaptcha/react-hcaptcha/pull/91 to be merged. It should make things a lot easier

**Comment by HoloPanio** [comment]
Any update on this?

**Comment by HoloPanio** [comment]
Is there any update on this?

**Comment by ajmnz** [comment]
That PR was merged, will wait until the package is updated on npm and then refactor this thing

**Pull request closed without merging**
