### PR TITLE
Custom 404 page

### PR DESCRIPTION
**Pull request by TheOtterlord**
Add a custom 404 page with links to common pages

404 preview

### CODE REVIEW

**Comment by HoloPanio** [comment]
How did you manage to fail the build step

**Comment by TheOtterlord** [comment]
Not sure. Maybe it's the yarn lockfile?

**Comment by HoloPanio** [comment]
It appears you have cloned the `dev` branch instead of the `overhaul` branch and you're trying to merge it into the `overhaul` branch.

**Comment by TheOtterlord** [comment]
Replaced with #63

**Pull request closed without merging**
